from __future__ import annotations

from urllib.parse import quote

from lunch_app.db import init_db
from lunch_app.repository import delete_restaurants_by_names, upsert_restaurant_by_name


BASE_LOCATION_NAME = "미래에셋증권빌딩"
BASE_LOCATION_ADDRESS = "서울 영등포구 국제금융로 56"

DEMO_RESTAURANT_NAMES = ["을지국밥", "사쿠라동", "포메이트"]
LEGACY_VARIANT_NAMES = [
    "Hanamdong Yeouido",
    "K55 송탄부대찌개 여의도본점",
    "MUTAN Yeouido Store",
    "MUTAN 여의도점",
    "마마된장 여의도IFC몰점",
    "마마스 IFC몰점",
    "쉐이크쉑 여의도IFC몰점",
    "아비꼬 여의도IFC몰점",
    "제일제면소 여의도IFC몰점",
    "차알 Cha R IFC몰점",
    "차알 여의도IFC몰점",
    "카페마마스 여의도IFC몰점",
    "콘타이 IFC몰점",
    "훠궈야 IFC몰점",
    "리스카페 여의도",
    "소이연남 브라이튼여의도",
]

NAME_NORMALIZATION_MAP = {
    "Hanamdong Yeouido": "한암동 여의도점",
    "K55 송탄부대찌개 여의도본점": "케이55 송탄부대찌개 여의도본점",
    "MUTAN Yeouido Store": "무탄 여의도점",
    "MUTAN 여의도점": "무탄 여의도점",
    "차알 Cha R IFC몰점": "차알 여의도IFC몰점",
    "리스카페 여의도": "리스카페 여의도점",
    "소이연남 브라이튼여의도": "소이연남 브라이튼여의도점",
}


def normalize_restaurant_name(name: str) -> str:
    normalized = NAME_NORMALIZATION_MAP.get(name, name)
    return normalized.replace("IFC", "아이에프씨")


def build_naver_search_url(name: str, address: str | None = None) -> str:
    query_parts = [name.strip()]
    if address:
        query_parts.append(address.strip())
    query = " ".join(part for part in query_parts if part)
    return f"https://map.naver.com/p/search/{quote(query)}"


def prepare_restaurant_payload(payload: dict) -> dict:
    normalized_name = normalize_restaurant_name(payload["name"])
    prepared = dict(payload)
    prepared["name"] = normalized_name
    prepared["naver_url"] = payload.get("naver_url") or build_naver_search_url(normalized_name, payload.get("address"))
    return prepared

CURATED_RESTAURANTS = [
    {
        "name": "진주집",
        "category": "한식",
        "distance_km": 0.9,
        "address": "서울 영등포구 국제금융로6길 33 지하 1층",
        "naver_url": "https://naver.me/FVbYBUtd",
        "price_level": "10000~20000원",
        "tags": "콩국수,칼국수,웨이팅",
        "note": "여의도 미래에셋증권빌딩 기준 도보권. source=https://makeitstop.tistory.com/60",
    },
    {
        "name": "영원식당",
        "category": "한식",
        "distance_km": 1.1,
        "address": "서울 영등포구 여의나루로 117 서울 상가 2층",
        "naver_url": "https://naver.me/FJ6W0PdH",
        "price_level": "10000~20000원",
        "tags": "수제비,감자전,노포",
        "note": "더현대 인근. source=https://makeitstop.tistory.com/60",
    },
    {
        "name": "희정식당",
        "category": "한식",
        "distance_km": 1.1,
        "address": "서울 영등포구 여의나루로 117",
        "naver_url": "https://naver.me/5D3t4aMv",
        "price_level": "10000~20000원",
        "tags": "부대찌개,노포",
        "note": "서울상가 지하. source=https://makeitstop.tistory.com/60",
    },
    {
        "name": "바스버거 여의도점",
        "category": "양식",
        "distance_km": 0.7,
        "address": "서울 영등포구 국제금융로 20 율촌빌딩 지하1층",
        "naver_url": "https://naver.me/Gz19RpM6",
        "price_level": "12000~20000원",
        "tags": "버거,감자칩",
        "note": "캐주얼 점심 후보. source=https://makeitstop.tistory.com/60",
    },
    {
        "name": "가양칼국수버섯매운탕",
        "category": "한식",
        "distance_km": 0.4,
        "address": "서울 영등포구 국제금융로 78 홍우빌딩 지하 1층",
        "naver_url": "https://naver.me/GLAPU8Zr",
        "price_level": "12000~22000원",
        "tags": "칼국수,버섯매운탕,샤브",
        "note": "미래에셋증권빌딩과 같은 대로변 권역. source=https://makeitstop.tistory.com/60",
    },
    {
        "name": "청수우동메밀냉면",
        "category": "분식",
        "distance_km": 1.3,
        "address": "서울 영등포구 국제금융로 112",
        "naver_url": "https://naver.me/GxR1UKb9",
        "price_level": "10000~15000원",
        "tags": "우동,메밀,분식",
        "note": "가벼운 점심용. source=https://makeitstop.tistory.com/60",
    },
    {
        "name": "소이연남 브라이튼여의도점",
        "category": "베트남",
        "distance_km": 0.5,
        "address": "서울 영등포구 국제금융로 39 지하1층 103호, 104호, 105호",
        "naver_url": "https://naver.me/xDjSwZVc",
        "price_level": "12000~18000원",
        "tags": "쌀국수,똠얌,브라이튼",
        "note": "브라이튼 지하 식당가. source=https://makeitstop.tistory.com/60",
    },
    {
        "name": "천가네옛날손짜장",
        "category": "중식",
        "distance_km": 0.8,
        "address": "서울 영등포구 국제금융로 86 롯데캐슬 아이비",
        "naver_url": "https://naver.me/FZ9YQXAp",
        "price_level": "9000~15000원",
        "tags": "수타짜장,짬뽕",
        "note": "오래된 중식 후보. source=https://makeitstop.tistory.com/60",
    },
    {
        "name": "화목순대국",
        "category": "한식",
        "distance_km": 1.4,
        "address": "서울 영등포구 여의대방로 383 1F",
        "naver_url": "https://naver.me/FAQxtcAg",
        "price_level": "10000~15000원",
        "tags": "순대국,웨이팅",
        "note": "대표적인 여의도 점심 맛집. source=https://makeitstop.tistory.com/60",
    },
    {
        "name": "리스카페 여의도점",
        "category": "양식",
        "distance_km": 0.5,
        "address": "서울 영등포구 국제금융로 39 브라이튼 여의도 103동 1층",
        "naver_url": "https://naver.me/xKzvTJZz",
        "price_level": "18000~30000원",
        "tags": "파스타,브런치,양식",
        "note": "브라이튼 여의도. source=https://2-ye-sung.tistory.com/",
    },
    {
        "name": "신홍러우 여의도점",
        "category": "중식",
        "distance_km": 0.5,
        "address": "서울 영등포구 국제금융로 39",
        "naver_url": "",
        "price_level": "15000~30000원",
        "tags": "중식,탕수육,브라이튼",
        "note": "브라이튼 지하 중식당. source=https://www.tabling.co.kr/place/677cd5d666de5f06988fec7a",
    },
    {
        "name": "단디만",
        "category": "한식",
        "distance_km": 0.9,
        "address": "서울 영등포구 국제금융로6길 33 여의도백화점 지하 1층",
        "naver_url": "",
        "price_level": "10000~15000원",
        "tags": "돼지국밥,여의도백화점",
        "note": "여의도백화점 지하 직장인 점심권. source=https://banjibbap.tistory.com/entry/%EA%B5%AD%EB%B0%A5-1",
    },
    {
        "name": "도스마스 여의도점",
        "category": "기타",
        "distance_km": 0.9,
        "address": "서울 영등포구 국제금융로6길 33 여의도백화점 지하 1층",
        "naver_url": "",
        "price_level": "10000~16000원",
        "tags": "부리또,멕시칸,여의도백화점",
        "note": "여의도백화점 지하 신규 점심 후보. source=https://banjibbap.tistory.com/entry/%EB%8F%84%EB%A7%88",
    },
    {
        "name": "옹기항아리수제비",
        "category": "한식",
        "distance_km": 0.6,
        "address": "서울 영등포구 국제금융로8길 34",
        "naver_url": "https://naver.me/FDnCUiw3",
        "price_level": "10000~15000원",
        "tags": "수제비,국물,직장인맛집",
        "note": "샛강역 방면 도보권. source=https://seon86.tistory.com/archive/20260124",
    },
    {
        "name": "차알 여의도IFC몰점",
        "category": "중식",
        "distance_km": 0.9,
        "address": "서울 영등포구 국제금융로 10 IFC몰",
        "naver_url": "",
        "price_level": "15000~25000원",
        "tags": "미국식중식,IFC몰",
        "note": "IFC몰 식당가 후보. source=https://14ship.tistory.com/entry/%EC%97%AC%EC%9D%98%EB%8F%84-IFC%EB%AA%B0-%EB%AF%B8%EA%B5%AD%EC%8B%9D-%EC%A4%91%EC%8B%9D-%EB%A0%88%EC%8A%A4%ED%86%A0%EB%9E%91-%EC%B0%A8%EC%95%8CCha-R",
    },
    {
        "name": "훠궈야 IFC몰점",
        "category": "중식",
        "distance_km": 0.9,
        "address": "서울 영등포구 국제금융로 10 IFC몰 L3 312호",
        "naver_url": "",
        "price_level": "16000~30000원",
        "tags": "훠궈,샤브,IFC몰",
        "note": "IFC몰 런치/회식 겸용. source=https://parkelf.tistory.com/227",
    },
    {
        "name": "마마된장 여의도IFC몰점",
        "category": "한식",
        "distance_km": 0.9,
        "address": "서울 영등포구 국제금융로 10 IFC몰",
        "naver_url": "",
        "price_level": "13000~22000원",
        "tags": "된장,한식,IFC몰",
        "note": "IFC몰 한식 점심 후보. source=search result based mention",
    },
    {
        "name": "콘타이 IFC몰점",
        "category": "태국",
        "distance_km": 0.9,
        "address": "서울 영등포구 국제금융로 10 IFC몰",
        "naver_url": "",
        "price_level": "15000~22000원",
        "tags": "태국음식,팟타이,IFC몰",
        "note": "IFC몰 동남아 점심 후보. source=search result based mention",
    },
    {
        "name": "제일제면소 여의도IFC몰점",
        "category": "한식",
        "distance_km": 0.9,
        "address": "서울 영등포구 국제금융로 10 IFC몰",
        "naver_url": "",
        "price_level": "12000~19000원",
        "tags": "국수,한식,IFC몰",
        "note": "IFC몰 면류 점심 후보. source=search result based mention",
    },
    {
        "name": "쉐이크쉑 여의도IFC몰점",
        "category": "양식",
        "distance_km": 0.9,
        "address": "서울 영등포구 국제금융로 10 IFC몰",
        "naver_url": "",
        "price_level": "12000~20000원",
        "tags": "버거,IFC몰",
        "note": "IFC몰 캐주얼 패스트 런치 후보. source=search result based mention",
    },
    {
        "name": "카페마마스 여의도IFC몰점",
        "category": "카페",
        "distance_km": 0.9,
        "address": "서울 영등포구 국제금융로 10 IFC몰",
        "naver_url": "",
        "price_level": "12000~20000원",
        "tags": "샌드위치,브런치,IFC몰",
        "note": "가벼운 브런치형 점심 후보. source=search result based mention",
    },
    {
        "name": "아비꼬 여의도IFC몰점",
        "category": "일식",
        "distance_km": 0.9,
        "address": "서울 영등포구 국제금융로 10 IFC몰",
        "naver_url": "",
        "price_level": "10000~15000원",
        "tags": "카레,일식,IFC몰",
        "note": "IFC몰 무난한 점심 후보. source=search result based mention",
    },
    {
        "name": "사보텐 여의도IFC몰점",
        "category": "일식",
        "distance_km": 0.9,
        "address": "서울 영등포구 국제금융로 10 IFC몰 B1",
        "naver_url": "",
        "price_level": "13000~20000원",
        "tags": "돈카츠,일식,IFC몰",
        "note": "IFC몰 지하 일식 돈카츠 후보.",
    },
    {
        "name": "고봉삼계탕 여의도점",
        "category": "한식",
        "distance_km": 0.8,
        "address": "서울 영등포구 여의도동 일대",
        "naver_url": "",
        "price_level": "16000~22000원",
        "tags": "삼계탕,보양식",
        "note": "여의도 직장인 보양식 점심 후보. source=https://www.keyzard.cc/register/nb/yeonsoos",
    },
    {
        "name": "프레퍼스 다이어트 푸드 여의도역직영점",
        "category": "기타",
        "distance_km": 1.0,
        "address": "서울 영등포구 여의도역 인근",
        "naver_url": "",
        "price_level": "10000~15000원",
        "tags": "샐러드,다이어트,포장",
        "note": "가벼운 점심/다이어트 후보. source=https://www.keyzard.cc/register/nb/yeonsoos",
    },
    {
        "name": "한가로이 2호점",
        "category": "한식",
        "distance_km": 1.1,
        "address": "서울 영등포구 여의도동 일대",
        "naver_url": "",
        "price_level": "11000~18000원",
        "tags": "솥밥,한식",
        "note": "가성비 솥밥 점심 후보. source=https://www.keyzard.cc/register/nb/yeonsoos",
    },
    {
        "name": "도깨비굴",
        "category": "양식",
        "distance_km": 1.0,
        "address": "서울 영등포구 여의도동 일대",
        "naver_url": "",
        "price_level": "18000~30000원",
        "tags": "파스타,레스토랑,데이트",
        "note": "분위기 있는 양식 후보. source=https://www.keyzard.cc/register/nb/yeonsoos",
    },
    {
        "name": "수정쌈밥 2호점",
        "category": "한식",
        "distance_km": 1.4,
        "address": "서울 영등포구 의사당대로 일대",
        "naver_url": "",
        "price_level": "10000~16000원",
        "tags": "쌈밥,제육,가성비",
        "note": "국회의사당역 쪽 점심 후보. source=https://www.keyzard.cc/register/nb/yeonsoos",
    },
    {
        "name": "여의도감",
        "category": "한식",
        "distance_km": 1.2,
        "address": "서울 영등포구 여의도동 일대",
        "naver_url": "",
        "price_level": "15000~25000원",
        "tags": "샤브샤브,한식,모임",
        "note": "샤브샤브/가족모임형 점심 후보. source=https://www.keyzard.cc/register/nb/yeonsoos",
    },
    {
        "name": "신송한식",
        "category": "한식",
        "distance_km": 0.9,
        "address": "서울 영등포구 여의나루로 67 신송빌딩",
        "naver_url": "",
        "price_level": "10000~16000원",
        "tags": "대구탕,한식,국물",
        "note": "직장인 점심 대구탕 후보. source=https://edowill.tistory.com/649",
    },
    {
        "name": "지리산 명가",
        "category": "한식",
        "distance_km": 0.9,
        "address": "서울 영등포구 여의나루로 67 신송빌딩 지하 1층",
        "naver_url": "",
        "price_level": "12000~18000원",
        "tags": "정식,제육,한식",
        "note": "신송빌딩 지하 한식 후보. source=https://banjibbap.tistory.com/entry/%EC%A0%95%EC%8B%9D",
    },
    {
        "name": "여의도 쌍대포",
        "category": "한식",
        "distance_km": 0.8,
        "address": "서울 영등포구 국제금융로6길 30 백상빌딩 1층",
        "naver_url": "",
        "price_level": "10000~15000원",
        "tags": "순두부,백상빌딩,웨이팅",
        "note": "순두부 점심 인기 후보. source=https://banjibbap.tistory.com/entry/%EC%8C%8D%EB%8C%80%ED%8F%AC",
    },
    {
        "name": "중화요리 홍콩",
        "category": "중식",
        "distance_km": 0.9,
        "address": "서울 영등포구 국제금융로6길 33 여의도백화점 지하 20,21호",
        "naver_url": "",
        "price_level": "10000~18000원",
        "tags": "짜장면,짬뽕,여의도백화점",
        "note": "여의도백화점 지하 중식 후보. source=https://banjibbap.tistory.com/entry/%EC%A4%91%EC%8B%9D",
    },
    {
        "name": "만나손칼국수",
        "category": "한식",
        "distance_km": 0.9,
        "address": "서울 영등포구 국제금융로6길 33 여의도백화점 지하 1층",
        "naver_url": "",
        "price_level": "10000~15000원",
        "tags": "칼국수,만두,여의도백화점",
        "note": "칼국수 대표 후보. source=https://banjibbap.tistory.com/entry/%EB%A7%8C%EB%82%98",
    },
    {
        "name": "별미볶음점 본점",
        "category": "한식",
        "distance_km": 0.9,
        "address": "서울 영등포구 국제금융로6길 33 여의도백화점 지하 1층",
        "naver_url": "",
        "price_level": "10000~17000원",
        "tags": "제육볶음,오삼볶음,여의도백화점",
        "note": "제육볶음 점심 인기 후보. source=https://betternbetter.tistory.com/28",
    },
    {
        "name": "여의도초장집",
        "category": "한식",
        "distance_km": 0.9,
        "address": "서울 영등포구 국제금융로6길 33 맨하튼빌딩 지하 1층",
        "naver_url": "",
        "price_level": "15000~25000원",
        "tags": "물회,해산물",
        "note": "물회/해산물 후보. source=https://banjibbap.tistory.com/entry/%EB%AC%BC%ED%9A%8C-1",
    },
    {
        "name": "너섬 칼국수",
        "category": "한식",
        "distance_km": 0.9,
        "address": "서울 영등포구 국제금융로6길 33 지하1층",
        "naver_url": "",
        "price_level": "10000~15000원",
        "tags": "칼국수,여의도백화점",
        "note": "칼국수/만두 점심 후보. source=https://banjibbap.tistory.com/entry/%EB%84%88%EC%84%AC2",
    },
    {
        "name": "푸드카페",
        "category": "분식",
        "distance_km": 0.8,
        "address": "서울 영등포구 여의나루로 42 1층",
        "naver_url": "",
        "price_level": "7000~12000원",
        "tags": "분식,김밥,24시간",
        "note": "가볍게 먹기 좋은 분식 후보. source=https://banjibbap.tistory.com/entry/%EB%B6%84%EC%8B%9D",
    },
    {
        "name": "광씨네 전주콩나물국밥",
        "category": "한식",
        "distance_km": 0.9,
        "address": "서울 영등포구 여의도동 일대",
        "naver_url": "",
        "price_level": "9000~13000원",
        "tags": "콩나물국밥,해장",
        "note": "직장인 점심 후보. source=https://dragon4.tistory.com/150",
    },
    {
        "name": "동우황태",
        "category": "한식",
        "distance_km": 0.9,
        "address": "서울 영등포구 여의도동 일대",
        "naver_url": "",
        "price_level": "10000~15000원",
        "tags": "황태국,한식,국물",
        "note": "직장인 국물 점심 후보. source=https://dragon4.tistory.com/150",
    },
    {
        "name": "기소야",
        "category": "일식",
        "distance_km": 0.9,
        "address": "서울 영등포구 여의도동 일대",
        "naver_url": "",
        "price_level": "10000~18000원",
        "tags": "우동,돈까스,일식",
        "note": "일식 면류/돈까스 후보. source=https://dragon4.tistory.com/150",
    },
    {
        "name": "자린고비",
        "category": "한식",
        "distance_km": 1.0,
        "address": "서울 영등포구 여의도동 일대",
        "naver_url": "",
        "price_level": "10000~16000원",
        "tags": "황태구이정식,집밥",
        "note": "집밥 느낌 정식 후보. source=https://dragon4.tistory.com/150",
    },
    {
        "name": "맛뜸",
        "category": "한식",
        "distance_km": 1.0,
        "address": "서울 영등포구 여의도동 일대",
        "naver_url": "",
        "price_level": "9000~15000원",
        "tags": "감자탕,뼈해장국",
        "note": "해장국/감자탕 후보. source=https://dragon4.tistory.com/150",
    },
    {
        "name": "솔솥",
        "category": "한식",
        "distance_km": 1.0,
        "address": "서울 영등포구 여의도동 일대",
        "naver_url": "",
        "price_level": "13000~19000원",
        "tags": "솥밥,한식",
        "note": "건강한 솥밥 점심 후보. source=https://dragon4.tistory.com/150",
    },
    {
        "name": "우직화",
        "category": "한식",
        "distance_km": 1.4,
        "address": "서울 영등포구 여의공원로 115 세우빌딩",
        "naver_url": "",
        "price_level": "10000~15000원",
        "tags": "김치찌개,제육",
        "note": "서여의도 가성비 한식 후보. source=https://blog.naver.com/PostView.nhn?blogId=txmarnxta&logNo=223697630730&redirect=Dlog&widgetTypeCall=true",
    },
    {
        "name": "다복집",
        "category": "한식",
        "distance_km": 1.5,
        "address": "서울 영등포구 은행로 58 삼도오피스텔 지하 101호",
        "naver_url": "",
        "price_level": "12000~20000원",
        "tags": "생선구이,계란찜",
        "note": "서여의도 한식 후보. source=https://blog.naver.com/PostView.nhn?blogId=txmarnxta&logNo=223697630730&redirect=Dlog&widgetTypeCall=true",
    },
    {
        "name": "신의주찹쌀순대 여의도공원점",
        "category": "한식",
        "distance_km": 1.6,
        "address": "서울 영등포구 여의서로 43 203호",
        "naver_url": "",
        "price_level": "10000~15000원",
        "tags": "순대국,해장",
        "note": "서여의도 순댓국 후보. source=https://blog.naver.com/PostView.nhn?blogId=txmarnxta&logNo=223697630730&redirect=Dlog&widgetTypeCall=true",
    },
    {
        "name": "금원삼계탕",
        "category": "한식",
        "distance_km": 1.7,
        "address": "서울 영등포구 국회대로70길 7 동아빌딩 지하1층 15호",
        "naver_url": "",
        "price_level": "12000~20000원",
        "tags": "삼계탕,닭칼국수",
        "note": "삼계탕/닭칼국수 후보. source=https://blog.naver.com/PostView.nhn?blogId=txmarnxta&logNo=223697630730&redirect=Dlog&widgetTypeCall=true",
    },
    {
        "name": "리153 중식뷔페",
        "category": "중식",
        "distance_km": 1.8,
        "address": "서울 영등포구 국회대로76가길 11 B1층 5호",
        "naver_url": "",
        "price_level": "10000~17000원",
        "tags": "중식뷔페,가성비",
        "note": "서여의도 중식뷔페 후보. source=https://blog.naver.com/PostView.nhn?blogId=txmarnxta&logNo=223697630730&redirect=Dlog&widgetTypeCall=true",
    },
    {
        "name": "겐카츠",
        "category": "일식",
        "distance_km": 1.5,
        "address": "서울 영등포구 은행로 54 110호",
        "naver_url": "",
        "price_level": "10000~16000원",
        "tags": "돈카츠,웨이팅",
        "note": "서여의도 돈카츠 후보. source=https://blog.naver.com/PostView.nhn?blogId=txmarnxta&logNo=223697630730&redirect=Dlog&widgetTypeCall=true",
    },
    {
        "name": "저스트텐동 여의도점",
        "category": "일식",
        "distance_km": 1.7,
        "address": "서울 영등포구 국회대로74길 20 맨하탄21리빙텔 지하 1층 108호",
        "naver_url": "",
        "price_level": "10000~18000원",
        "tags": "텐동,일식",
        "note": "텐동 점심 후보. source=https://blog.naver.com/PostView.nhn?blogId=txmarnxta&logNo=223697630730&redirect=Dlog&widgetTypeCall=true",
    },
    {
        "name": "바스버거 국회의사당점",
        "category": "양식",
        "distance_km": 1.8,
        "address": "서울 영등포구 국회대로 780 LG여의도에클라드 지하1층",
        "naver_url": "",
        "price_level": "12000~20000원",
        "tags": "버거,국회의사당",
        "note": "버거 점심 후보. source=https://blog.naver.com/PostView.nhn?blogId=txmarnxta&logNo=223697630730&redirect=Dlog&widgetTypeCall=true",
    },
    {
        "name": "이수쭈꾸미 서여의도점",
        "category": "한식",
        "distance_km": 1.7,
        "address": "서울 영등포구 국회대로74길 20 2층 208호, 209호",
        "naver_url": "",
        "price_level": "12000~22000원",
        "tags": "쭈꾸미,볶음밥",
        "note": "쭈꾸미 점심 후보. source=https://blog.naver.com/PostView.nhn?blogId=txmarnxta&logNo=223697630730&redirect=Dlog&widgetTypeCall=true",
    },
    {
        "name": "종로계림닭도리탕원조 국회의사당점",
        "category": "한식",
        "distance_km": 1.7,
        "address": "서울 영등포구 국회대로74길 20 2층",
        "naver_url": "",
        "price_level": "12000~25000원",
        "tags": "닭도리탕,마늘",
        "note": "닭볶음탕 후보. source=https://blog.naver.com/PostView.nhn?blogId=txmarnxta&logNo=223697630730&redirect=Dlog&widgetTypeCall=true",
    },
    {
        "name": "반피쏭",
        "category": "태국",
        "distance_km": 1.5,
        "address": "서울 영등포구 은행로 54 지하1층103호",
        "naver_url": "",
        "price_level": "12000~22000원",
        "tags": "팟타이,쌀국수,똠얌",
        "note": "서여의도 태국음식 후보. source=https://blog.naver.com/PostView.nhn?blogId=txmarnxta&logNo=223697630730&redirect=Dlog&widgetTypeCall=true",
    },
    {
        "name": "진진만두 국회점",
        "category": "한식",
        "distance_km": 1.8,
        "address": "서울 영등포구 국회대로72길 11 프린스텔",
        "naver_url": "",
        "price_level": "15000~30000원",
        "tags": "만두,어복쟁반,수육",
        "note": "국회의사당권 인기 만두집. source=https://little-cat.tistory.com/entry/%EC%84%9C%EC%97%AC%EC%9D%98%EB%8F%84-%EC%A0%90%EC%8B%AC-%EB%B2%A0%EC%8A%A4%ED%8A%B8-10-%EC%88%9C%EC%9C%84-%EC%B6%94%EC%B2%9C",
    },
    {
        "name": "심경희라라랜드 여의도",
        "category": "한식",
        "distance_km": 1.7,
        "address": "서울 영등포구 국회대로66길 19 102호",
        "naver_url": "",
        "price_level": "18000~35000원",
        "tags": "소고기구이,회식",
        "note": "국회의사당역 고기 후보. source=https://little-cat.tistory.com/entry/%EC%84%9C%EC%97%AC%EC%9D%98%EB%8F%84-%EC%A0%90%EC%8B%AC-%EB%B2%A0%EC%8A%A4%ED%8A%B8-10-%EC%88%9C%EC%9C%84-%EC%B6%94%EC%B2%9C",
    },
    {
        "name": "차이윤 서여의도점",
        "category": "중식",
        "distance_km": 1.8,
        "address": "서울 영등포구 국회대로 800 여의도파라곤 1층 113호",
        "naver_url": "",
        "price_level": "13000~25000원",
        "tags": "중식,마라짬뽕,볶음밥",
        "note": "서여의도 중식 다이닝 후보. source=https://little-cat.tistory.com/entry/%EC%84%9C%EC%97%AC%EC%9D%98%EB%8F%84-%EC%A0%90%EC%8B%AC-%EB%B2%A0%EC%8A%A4%ED%8A%B8-10-%EC%88%9C%EC%9C%84-%EC%B6%94%EC%B2%9C",
    },
    {
        "name": "비욘드비엣남 국회의사당점",
        "category": "베트남",
        "distance_km": 1.7,
        "address": "서울 영등포구 의사당대로 26 107호",
        "naver_url": "",
        "price_level": "11000~18000원",
        "tags": "쌀국수,베트남음식",
        "note": "서여의도 베트남 후보. source=https://little-cat.tistory.com/entry/%EC%84%9C%EC%97%AC%EC%9D%98%EB%8F%84-%EC%A0%90%EC%8B%AC-%EB%B2%A0%EC%8A%A4%ED%8A%B8-10-%EC%88%9C%EC%9C%84-%EC%B6%94%EC%B2%9C",
    },
    {
        "name": "이태원천상 서여의도점",
        "category": "일식",
        "distance_km": 1.9,
        "address": "서울 영등포구 국회대로68길 17 해운빌딩 지하1층",
        "naver_url": "",
        "price_level": "13000~25000원",
        "tags": "이자카야,회식,점심",
        "note": "점심 겸 저녁 가능 후보. source=https://little-cat.tistory.com/entry/%EC%84%9C%EC%97%AC%EC%9D%98%EB%8F%84-%EC%A0%90%EC%8B%AC-%EB%B2%A0%EC%8A%A4%ED%8A%B8-10-%EC%88%9C%EC%9C%84-%EC%B6%94%EC%B2%9C",
    },
    {
        "name": "37.5 시그니처 여의도점",
        "category": "양식",
        "distance_km": 1.7,
        "address": "서울 영등포구 의사당대로 38 더샾아일랜드파크 101동 106호",
        "naver_url": "",
        "price_level": "15000~25000원",
        "tags": "브런치,양식",
        "note": "브런치형 점심 후보. source=https://little-cat.tistory.com/entry/%EC%84%9C%EC%97%AC%EC%9D%98%EB%8F%84-%EC%A0%90%EC%8B%AC-%EB%B2%A0%EC%8A%A4%ED%8A%B8-10-%EC%88%9C%EC%9C%84-%EC%B6%94%EC%B2%9C",
    },
    {
        "name": "옥된장 서여의도점",
        "category": "한식",
        "distance_km": 1.7,
        "address": "서울 영등포구 국회대로70길 7 제지하1층 16호",
        "naver_url": "",
        "price_level": "11000~18000원",
        "tags": "된장전골,한식",
        "note": "서여의도 한식 후보. source=https://little-cat.tistory.com/entry/%EC%84%9C%EC%97%AC%EC%9D%98%EB%8F%84-%EC%A0%90%EC%8B%AC-%EB%B2%A0%EC%8A%A4%ED%8A%B8-10-%EC%88%9C%EC%9C%84-%EC%B6%94%EC%B2%9C",
    },
    {
        "name": "일미온",
        "category": "한식",
        "distance_km": 1.8,
        "address": "서울 영등포구 국회대로70길 15-1 2층 204-1호",
        "naver_url": "",
        "price_level": "10000~16000원",
        "tags": "국밥,해장국",
        "note": "국밥 점심 후보. source=https://little-cat.tistory.com/entry/%EC%84%9C%EC%97%AC%EC%9D%98%EB%8F%84-%EC%A0%90%EC%8B%AC-%EB%B2%A0%EC%8A%A4%ED%8A%B8-10-%EC%88%9C%EC%9C%84-%EC%B6%94%EC%B2%9C",
    },
    {
        "name": "한국수 강릉장칼집",
        "category": "한식",
        "distance_km": 1.8,
        "address": "서울 영등포구 의사당대로 8 지하1층 110호",
        "naver_url": "",
        "price_level": "11000~18000원",
        "tags": "장칼국수,수육",
        "note": "장칼국수 점심 후보. source=https://little-cat.tistory.com/entry/%EC%84%9C%EC%97%AC%EC%9D%98%EB%8F%84-%EC%A0%90%EC%8B%AC-%EB%B2%A0%EC%8A%A4%ED%8A%B8-10-%EC%88%9C%EC%9C%84-%EC%B6%94%EC%B2%9C",
    },
    {
        "name": "마초갈비",
        "category": "한식",
        "distance_km": 1.6,
        "address": "서울 영등포구 여의도동 더샵아일랜드 건물 1층",
        "naver_url": "",
        "price_level": "10000~22000원",
        "tags": "제육쌈밥,고등어조림",
        "note": "국회의사당역 점심 후보. source=https://story-2.tistory.com/entry/%EA%B5%AD%ED%9A%8C%EC%9D%98%EC%82%AC%EB%8B%B9%EC%A0%90%EC%8B%AC",
    },
    {
        "name": "해담채",
        "category": "한식",
        "distance_km": 1.9,
        "address": "서울 영등포구 은행로 30 중소기업중앙회",
        "naver_url": "",
        "price_level": "20000~40000원",
        "tags": "한정식,모임",
        "note": "중앙회 건물 한정식 후보. source=https://future-trader.tistory.com/68",
    },
    {
        "name": "금화쿵푸",
        "category": "중식",
        "distance_km": 1.9,
        "address": "서울 영등포구 정우빌딩 지하 일대",
        "naver_url": "",
        "price_level": "10000~18000원",
        "tags": "마라탕,마라샹궈",
        "note": "서여의도 마라탕 후보. source=https://behs.tistory.com/entry/%EC%84%9C%EC%97%AC%EC%9D%98%EB%8F%84-%EA%B8%88%ED%99%94%EC%BF%B5%ED%91%B8-%EB%A6%AC%EB%B7%B0",
    },
    {
        "name": "삼보정",
        "category": "한식",
        "distance_km": 0.9,
        "address": "서울 영등포구 여의도동 35-5 여의도종합상가 1층",
        "naver_url": "",
        "price_level": "10000~17000원",
        "tags": "청국장,찌개",
        "note": "청국장 유명 후보. source=https://passja.tistory.com/112",
    },
    {
        "name": "타마스시",
        "category": "일식",
        "distance_km": 1.7,
        "address": "서울 영등포구 여의도동 13-21 맨해튼21리빙텔",
        "naver_url": "",
        "price_level": "30000~70000원",
        "tags": "스시,오마카세",
        "note": "고급 일식 후보. source=https://passja.tistory.com/112",
    },
    {
        "name": "진진만두국",
        "category": "한식",
        "distance_km": 0.6,
        "address": "서울 영등포구 여의도동 36-4 오륜빌딩 3층",
        "naver_url": "",
        "price_level": "12000~20000원",
        "tags": "만둣국,부추전",
        "note": "만둣국 후보. source=https://passja.tistory.com/112",
    },
    {
        "name": "정인면옥",
        "category": "한식",
        "distance_km": 1.7,
        "address": "서울 영등포구 국회대로76길 10 기독교 한국침례회 총회빌딩 1층",
        "naver_url": "",
        "price_level": "14000~35000원",
        "tags": "평양냉면,수육",
        "note": "평양냉면 대표 후보. source=https://passja.tistory.com/112",
    },
    {
        "name": "다미",
        "category": "일식",
        "distance_km": 0.6,
        "address": "서울 영등포구 여의도동 36-4 오륜빌딩",
        "naver_url": "",
        "price_level": "12000~22000원",
        "tags": "생선구이,일식",
        "note": "생선구이 점심 후보. source=https://passja.tistory.com/112",
    },
    {
        "name": "하쯔호",
        "category": "일식",
        "distance_km": 1.3,
        "address": "서울 영등포구 여의도동 61 금호리첸시아 지하 1층",
        "naver_url": "",
        "price_level": "45000~100000원",
        "tags": "스시,오마카세",
        "note": "고급 스시 후보. source=https://passja.tistory.com/112",
    },
    {
        "name": "서궁",
        "category": "중식",
        "distance_km": 0.4,
        "address": "서울 영등포구 여의도동 43-4 홍우빌딩 1층",
        "naver_url": "",
        "price_level": "11000~35000원",
        "tags": "군만두,오향장육",
        "note": "로컬 중식당 후보. source=https://passja.tistory.com/112",
    },
    {
        "name": "세상의 모든 아침",
        "category": "양식",
        "distance_km": 1.4,
        "address": "서울 영등포구 여의도동 28-1 전경련회관 50, 51F",
        "naver_url": "",
        "price_level": "20000~60000원",
        "tags": "브런치,뷰,파스타",
        "note": "전경련회관 뷰 맛집 후보. source=https://passja.tistory.com/112",
    },
    {
        "name": "백리향",
        "category": "중식",
        "distance_km": 1.9,
        "address": "서울 영등포구 63로 50 한화금융센터_63 57층",
        "naver_url": "",
        "price_level": "60000원 이상",
        "tags": "중식,고급,63빌딩",
        "note": "63빌딩 고급 중식 후보. source=https://lookatmoney2.tistory.com/entry/%EC%84%9C%EC%9A%B8-%EC%98%81%EB%93%B1%ED%8F%AC%EA%B5%AC-%EC%97%AC%EC%9D%98%EB%8F%84-%EB%A7%9B%EC%A7%91-%EB%B2%A0%EC%8A%A4%ED%8A%B810%EB%B8%94%EB%A3%A8%EB%A6%AC%EB%B3%B8-%EB%A7%9B%EC%A7%91",
    },
    {
        "name": "마마리다이닝",
        "category": "한식",
        "distance_km": 0.9,
        "address": "서울 영등포구 국제금융로 10 IFC몰 L3층 306호",
        "naver_url": "",
        "price_level": "17000~30000원",
        "tags": "한식다이닝,IFC몰",
        "note": "IFC몰 한식 다이닝 후보. source=https://lookatmoney2.tistory.com/entry/%EC%84%9C%EC%9A%B8-%EC%98%81%EB%93%B1%ED%8F%AC%EA%B5%AC-%EC%97%AC%EC%9D%98%EB%8F%84-%EB%A7%9B%EC%A7%91-%EB%B2%A0%EC%8A%A4%ED%8A%B810%EB%B8%94%EB%A3%A8%EB%A6%AC%EB%B3%B8-%EB%A7%9B%EC%A7%91",
    },
    {
        "name": "무탄 여의도점",
        "category": "중식",
        "distance_km": 1.0,
        "address": "서울 영등포구 여의도역 1번 출구 인근",
        "naver_url": "",
        "price_level": "30000원 이상",
        "tags": "중식,딤섬,룸",
        "note": "고급 중식 후보. source=https://tour33.tistory.com/m/entry/%EC%97%AC%EC%9D%98%EB%8F%84-%EB%A7%9B%EC%A7%91-%EB%B2%A0%EC%8A%A4%ED%8A%B810",
    },
    {
        "name": "화해당 여의도점",
        "category": "한식",
        "distance_km": 1.8,
        "address": "서울 영등포구 국회의사당 앞 일대",
        "naver_url": "",
        "price_level": "30000원 이상",
        "tags": "간장게장,돌솥밥",
        "note": "게장/한식 고급 후보. source=https://tour33.tistory.com/m/entry/%EC%97%AC%EC%9D%98%EB%8F%84-%EB%A7%9B%EC%A7%91-%EB%B2%A0%EC%8A%A4%ED%8A%B810",
    },
    {
        "name": "MUTAN Yeouido Store",
        "category": "중식",
        "distance_km": 1.0,
        "address": "서울 영등포구 TP타워 2층",
        "naver_url": "",
        "price_level": "30000원 이상",
        "tags": "딤섬,유린기,트러플짜장면",
        "note": "영문 표기 기준 후보. source=https://insight24233.tistory.com/entry/%F0%9F%8D%BD%EF%B8%8F-2026-%EC%97%AC%EC%9D%98%EB%8F%84-%EB%A7%9B%EC%A7%91-%EC%B6%94%EC%B2%9C-TOP-10-%EC%A7%81%EC%9E%A5%EC%9D%B8%C2%B7%EB%8D%B0%EC%9D%B4%ED%8A%B8%C2%B7%ED%98%BC%EB%B0%A5%EA%B9%8C%EC%A7%80-%EC%99%84%EB%B2%BD-%EC%A0%95%EB%A6%AC",
    },
    {
        "name": "고우가 여의도점",
        "category": "한식",
        "distance_km": 1.4,
        "address": "서울 영등포구 전경련회관 지하",
        "naver_url": "",
        "price_level": "30000원 이상",
        "tags": "한우코스,한식오마카세",
        "note": "프리미엄 한식 후보. source=https://insight24233.tistory.com/entry/%F0%9F%8D%BD%EF%B8%8F-2026-%EC%97%AC%EC%9D%98%EB%8F%84-%EB%A7%9B%EC%A7%91-%EC%B6%94%EC%B2%9C-TOP-10-%EC%A7%81%EC%9E%A5%EC%9D%B8%C2%B7%EB%8D%B0%EC%9D%B4%ED%8A%B8%C2%B7%ED%98%BC%EB%B0%A5%EA%B9%8C%EC%A7%80-%EC%99%84%EB%B2%BD-%EC%A0%95%EB%A6%AC",
    },
    {
        "name": "소울한우 여의도샛강역점",
        "category": "한식",
        "distance_km": 0.8,
        "address": "서울 영등포구 샛강역 인근",
        "naver_url": "",
        "price_level": "30000원 이상",
        "tags": "한우,구이",
        "note": "샛강역 고기 후보. source=https://insight24233.tistory.com/entry/%F0%9F%8D%BD%EF%B8%8F-2026-%EC%97%AC%EC%9D%98%EB%8F%84-%EB%A7%9B%EC%A7%91-%EC%B6%94%EC%B2%9C-TOP-10-%EC%A7%81%EC%9E%A5%EC%9D%B8%C2%B7%EB%8D%B0%EC%9D%B4%ED%8A%B8%C2%B7%ED%98%BC%EB%B0%A5%EA%B9%8C%EC%A7%80-%EC%99%84%EB%B2%BD-%EC%A0%95%EB%A6%AC",
    },
    {
        "name": "K55 송탄부대찌개 여의도본점",
        "category": "한식",
        "distance_km": 0.7,
        "address": "서울 영등포구 국제금융로 인근",
        "naver_url": "",
        "price_level": "10000~16000원",
        "tags": "부대찌개,회전율",
        "note": "부대찌개 점심 후보. source=https://insight24233.tistory.com/entry/%F0%9F%8D%BD%EF%B8%8F-2026-%EC%97%AC%EC%9D%98%EB%8F%84-%EB%A7%9B%EC%A7%91-%EC%B6%94%EC%B2%9C-TOP-10-%EC%A7%81%EC%9E%A5%EC%9D%B8%C2%B7%EB%8D%B0%EC%9D%B4%ED%8A%B8%C2%B7%ED%98%BC%EB%B0%A5%EA%B9%8C%EC%A7%80-%EC%99%84%EB%B2%BD-%EC%A0%95%EB%A6%AC",
    },
    {
        "name": "을지다락 여의도",
        "category": "양식",
        "distance_km": 1.1,
        "address": "서울 영등포구 여의나루역 근처",
        "naver_url": "",
        "price_level": "15000~25000원",
        "tags": "오므라이스,크림파스타",
        "note": "감성 양식 후보. source=https://insight24233.tistory.com/entry/%F0%9F%8D%BD%EF%B8%8F-2026-%EC%97%AC%EC%9D%98%EB%8F%84-%EB%A7%9B%EC%A7%91-%EC%B6%94%EC%B2%9C-TOP-10-%EC%A7%81%EC%9E%A5%EC%9D%B8%C2%B7%EB%8D%B0%EC%9D%B4%ED%8A%B8%C2%B7%ED%98%BC%EB%B0%A5%EA%B9%8C%EC%A7%80-%EC%99%84%EB%B2%BD-%EC%A0%95%EB%A6%AC",
    },
    {
        "name": "Hanamdong Yeouido",
        "category": "한식",
        "distance_km": 1.0,
        "address": "서울 영등포구 여의도 파이낸스타워 4층",
        "naver_url": "",
        "price_level": "25000원 이상",
        "tags": "한식코스,프리미엄",
        "note": "영문 표기 프리미엄 한식 후보. source=https://insight24233.tistory.com/entry/%F0%9F%8D%BD%EF%B8%8F-2026-%EC%97%AC%EC%9D%98%EB%8F%84-%EB%A7%9B%EC%A7%91-%EC%B6%94%EC%B2%9C-TOP-10-%EC%A7%81%EC%9E%A5%EC%9D%B8%C2%B7%EB%8D%B0%EC%9D%B4%ED%8A%B8%C2%B7%ED%98%BC%EB%B0%A5%EA%B9%8C%EC%A7%80-%EC%99%84%EB%B2%BD-%EC%A0%95%EB%A6%AC",
    },
    {
        "name": "나무가든 동여의도점",
        "category": "한식",
        "distance_km": 1.1,
        "address": "서울 영등포구 여의도 동쪽 라인",
        "naver_url": "",
        "price_level": "25000원 이상",
        "tags": "한우구이,갈비",
        "note": "고기 점심/회식 후보. source=https://insight24233.tistory.com/entry/%F0%9F%8D%BD%EF%B8%8F-2026-%EC%97%AC%EC%9D%98%EB%8F%84-%EB%A7%9B%EC%A7%91-%EC%B6%94%EC%B2%9C-TOP-10-%EC%A7%81%EC%9E%A5%EC%9D%B8%C2%B7%EB%8D%B0%EC%9D%B4%ED%8A%B8%C2%B7%ED%98%BC%EB%B0%A5%EA%B9%8C%EC%A7%80-%EC%99%84%EB%B2%BD-%EC%A0%95%EB%A6%AC",
    },
    {
        "name": "소금식당",
        "category": "기타",
        "distance_km": 0.8,
        "address": "서울 영등포구 샛강역 인근",
        "naver_url": "",
        "price_level": "15000~25000원",
        "tags": "안주,하이볼",
        "note": "식사 겸 2차 후보. source=https://insight24233.tistory.com/entry/%F0%9F%8D%BD%EF%B8%8F-2026-%EC%97%AC%EC%9D%98%EB%8F%84-%EB%A7%9B%EC%A7%91-%EC%B6%94%EC%B2%9C-TOP-10-%EC%A7%81%EC%9E%A5%EC%9D%B8%C2%B7%EB%8D%B0%EC%9D%B4%ED%8A%B8%C2%B7%ED%98%BC%EB%B0%A5%EA%B9%8C%EC%A7%80-%EC%99%84%EB%B2%BD-%EC%A0%95%EB%A6%AC",
    },
    {
        "name": "전설의우대갈비 여의도",
        "category": "한식",
        "distance_km": 1.8,
        "address": "서울 영등포구 국회의사당 인근",
        "naver_url": "",
        "price_level": "25000원 이상",
        "tags": "우대갈비,고기",
        "note": "갈비 전문 후보. source=https://insight24233.tistory.com/entry/%F0%9F%8D%BD%EF%B8%8F-2026-%EC%97%AC%EC%9D%98%EB%8F%84-%EB%A7%9B%EC%A7%91-%EC%B6%94%EC%B2%9C-TOP-10-%EC%A7%81%EC%9E%A5%EC%9D%B8%C2%B7%EB%8D%B0%EC%9D%B4%ED%8A%B8%C2%B7%ED%98%BC%EB%B0%A5%EA%B9%8C%EC%A7%80-%EC%99%84%EB%B2%BD-%EC%A0%95%EB%A6%AC",
    },
    {
        "name": "MUTAN 여의도점",
        "category": "중식",
        "distance_km": 1.0,
        "address": "서울 영등포구 TP타워 2층",
        "naver_url": "",
        "price_level": "30000원 이상",
        "tags": "중식,딤섬,트러플짜장",
        "note": "한글/영문 혼용 검색 대비 별도 후보. source=https://insight24233.tistory.com/entry/%F0%9F%8D%BD%EF%B8%8F-2026-%EC%97%AC%EC%9D%98%EB%8F%84-%EB%A7%9B%EC%A7%91-%EC%B6%94%EC%B2%9C-TOP-10-%EC%A7%81%EC%9E%A5%EC%9D%B8%C2%B7%EB%8D%B0%EC%9D%B4%ED%8A%B8%C2%B7%ED%98%BC%EB%B0%A5%EA%B9%8C%EC%A7%80-%EC%99%84%EB%B2%BD-%EC%A0%95%EB%A6%AC",
    },
    {
        "name": "차알 Cha R IFC몰점",
        "category": "중식",
        "distance_km": 0.9,
        "address": "서울 영등포구 국제금융로 10 IFC몰",
        "naver_url": "",
        "price_level": "15000~25000원",
        "tags": "미국식중식,IFC몰",
        "note": "영문 브랜드 표기 후보. source=https://14ship.tistory.com/entry/%EC%97%AC%EC%9D%98%EB%8F%84-IFC%EB%AA%B0-%EB%AF%B8%EA%B5%AD%EC%8B%9D-%EC%A4%91%EC%8B%9D-%EB%A0%88%EC%8A%A4%ED%86%A0%EB%9E%91-%EC%B0%A8%EC%95%8CCha-R",
    },
    {
        "name": "리스카페 여의도",
        "category": "양식",
        "distance_km": 0.5,
        "address": "서울 영등포구 국제금융로 39 브라이튼 여의도",
        "naver_url": "https://naver.me/xKzvTJZz",
        "price_level": "18000~30000원",
        "tags": "파스타,브런치",
        "note": "검색 표기 변형 대응. source=https://2-ye-sung.tistory.com/",
    },
    {
        "name": "소이연남 브라이튼여의도",
        "category": "베트남",
        "distance_km": 0.5,
        "address": "서울 영등포구 국제금융로 39 지하1층",
        "naver_url": "https://naver.me/xDjSwZVc",
        "price_level": "12000~18000원",
        "tags": "쌀국수,똠얌",
        "note": "브랜드 표기 변형 대응. source=https://banjibbap.tistory.com/entry/%EC%86%8C%EC%9D%B4",
    },
    {
        "name": "우상화로구이",
        "category": "한식",
        "distance_km": 1.4,
        "address": "서울 영등포구 여의도 파이낸스타워 일대",
        "naver_url": "",
        "price_level": "30000원 이상",
        "tags": "소고기,화로구이",
        "note": "여의도 소고기 맛집 언급 후보. source=https://www.keyzard.cc/register/nb/yeonsoos",
    },
    {
        "name": "해화동",
        "category": "한식",
        "distance_km": 1.3,
        "address": "서울 영등포구 월드비전 건물 지하 1층",
        "naver_url": "",
        "price_level": "20000~35000원",
        "tags": "꽃게탕,해산물",
        "note": "회식형 해산물 후보. source=https://www.keyzard.cc/register/nb/yeonsoos",
    },
    {
        "name": "천상한우 여의도",
        "category": "한식",
        "distance_km": 1.6,
        "address": "서울 영등포구 대산빌딩 지하1층",
        "naver_url": "",
        "price_level": "30000원 이상",
        "tags": "한우,룸식당",
        "note": "여의도 한우 후보. source=https://www.keyzard.cc/register/nb/yeonsoos",
    },
    {
        "name": "향촌흑염소 국회의사당직영점",
        "category": "한식",
        "distance_km": 1.9,
        "address": "서울 영등포구 대하빌딩 1층",
        "naver_url": "",
        "price_level": "20000~40000원",
        "tags": "흑염소,곰탕,룸식당",
        "note": "서여의도 보양식 후보. source=https://www.keyzard.cc/register/nb/yeonsoos",
    },
    {
        "name": "프레퍼스 여의도역직영점",
        "category": "기타",
        "distance_km": 1.0,
        "address": "서울 영등포구 여의도역 5번 출구 인근",
        "naver_url": "",
        "price_level": "10000~15000원",
        "tags": "샐러드,다이어트",
        "note": "프레퍼스 표기 변형 대응. source=https://www.keyzard.cc/register/nb/yeonsoos",
    },
    {
        "name": "한가로이",
        "category": "한식",
        "distance_km": 1.1,
        "address": "서울 영등포구 여의도동 일대",
        "naver_url": "",
        "price_level": "11000~18000원",
        "tags": "솥밥,한식",
        "note": "한가로이 계열 후보. source=https://www.keyzard.cc/register/nb/yeonsoos",
    },
    {
        "name": "마마스 IFC몰점",
        "category": "카페",
        "distance_km": 0.9,
        "address": "서울 영등포구 국제금융로 10 IFC몰",
        "naver_url": "",
        "price_level": "12000~20000원",
        "tags": "샌드위치,브런치",
        "note": "카페마마스 표기 축약 대응 후보. source=search result based mention",
    },
    {
        "name": "진가",
        "category": "한식",
        "distance_km": 0.8,
        "address": "서울 영등포구 국제금융로6길 30 백상빌딩 1층",
        "naver_url": "",
        "price_level": "10000~17000원",
        "tags": "김치전골,백상빌딩",
        "note": "백상빌딩 점심 후보. source=https://banjibbap.tistory.com/entry/%EC%A7%84%EA%B0%80",
    },
    {
        "name": "킴스라이스",
        "category": "분식",
        "distance_km": 0.9,
        "address": "서울 영등포구 여의도역 6번 출구 앞 아일렉스 1층",
        "naver_url": "",
        "price_level": "7000~13000원",
        "tags": "김밥,분식,포장",
        "note": "김밥 점심 후보. source=https://story-2.tistory.com/entry/%EC%97%AC%EC%9D%98%EB%8F%84-%ED%82%B4%EC%8A%A4%EB%9D%BC%EC%9D%B4%EC%8A%A4-%EA%B9%80%EB%B0%A5-%EB%A7%9B%EC%A7%91",
    },

    # ── 베트남 (추가) ────────────────────────────────────────────────────────
    {
        "name": "포29 여의도점",
        "category": "베트남",
        "distance_km": 1.0,
        "address": "서울 영등포구 여의도동",
        "naver_url": "",
        "price_level": "10000~15000원",
        "tags": "쌀국수,베트남,체인",
        "note": "PHO29 체인. 여의도역 인근.",
    },
    {
        "name": "에머이 여의도점",
        "category": "베트남",
        "distance_km": 1.1,
        "address": "서울 영등포구 여의도동",
        "naver_url": "",
        "price_level": "11000~16000원",
        "tags": "쌀국수,반미,베트남",
        "note": "에머이 체인. 쌀국수·반미 전문.",
    },
    {
        "name": "하노이키친 여의도점",
        "category": "베트남",
        "distance_km": 0.9,
        "address": "서울 영등포구 여의도동",
        "naver_url": "",
        "price_level": "11000~16000원",
        "tags": "쌀국수,베트남,런치",
        "note": "여의도 직장인 쌀국수 점심.",
    },
    {
        "name": "미스사이공 여의도점",
        "category": "베트남",
        "distance_km": 1.2,
        "address": "서울 영등포구 여의대방로 일대",
        "naver_url": "",
        "price_level": "12000~18000원",
        "tags": "쌀국수,반미,베트남",
        "note": "미스사이공 체인.",
    },
    {
        "name": "쌀국수집",
        "category": "베트남",
        "distance_km": 0.8,
        "address": "서울 영등포구 국제금융로 일대",
        "naver_url": "",
        "price_level": "10000~14000원",
        "tags": "쌀국수,베트남,가성비",
        "note": "여의도 쌀국수 로컬맛집.",
    },
    {
        "name": "반미반 여의도점",
        "category": "베트남",
        "distance_km": 1.0,
        "address": "서울 영등포구 여의도동",
        "naver_url": "",
        "price_level": "9000~14000원",
        "tags": "반미,베트남,가벼운점심",
        "note": "반미앤코 계열 여의도점.",
    },
    {
        "name": "월남쌈 여의도점",
        "category": "베트남",
        "distance_km": 1.1,
        "address": "서울 영등포구 여의나루로 일대",
        "naver_url": "",
        "price_level": "11000~16000원",
        "tags": "월남쌈,베트남,건강식",
        "note": "여의도 베트남 건강식 점심.",
    },
    {
        "name": "포스트 여의도점",
        "category": "베트남",
        "distance_km": 0.9,
        "address": "서울 영등포구 여의도동",
        "naver_url": "",
        "price_level": "10000~15000원",
        "tags": "쌀국수,베트남",
        "note": "여의도 쌀국수 점심 후보.",
    },

    # ── 태국 (추가) ──────────────────────────────────────────────────────────
    {
        "name": "씨암키친 여의도점",
        "category": "태국",
        "distance_km": 1.0,
        "address": "서울 영등포구 여의도동",
        "naver_url": "",
        "price_level": "12000~20000원",
        "tags": "팟타이,태국,런치",
        "note": "여의도 태국 식당.",
    },
    {
        "name": "타이오키드 여의도점",
        "category": "태국",
        "distance_km": 1.1,
        "address": "서울 영등포구 여의도동",
        "naver_url": "",
        "price_level": "12000~18000원",
        "tags": "태국,팟타이,볶음",
        "note": "타이오키드 체인.",
    },
    {
        "name": "코코이야 여의도점",
        "category": "태국",
        "distance_km": 0.9,
        "address": "서울 영등포구 국제금융로 일대",
        "naver_url": "",
        "price_level": "11000~17000원",
        "tags": "태국,코코넛,카레",
        "note": "코코이야 체인 여의도.",
    },
    {
        "name": "방콕소녀 여의도점",
        "category": "태국",
        "distance_km": 1.0,
        "address": "서울 영등포구 여의도동",
        "naver_url": "",
        "price_level": "11000~17000원",
        "tags": "태국,볶음밥,쌀국수",
        "note": "방콕소녀 체인.",
    },
    {
        "name": "어썸타이 여의도점",
        "category": "태국",
        "distance_km": 1.2,
        "address": "서울 영등포구 여의대방로 일대",
        "naver_url": "",
        "price_level": "12000~18000원",
        "tags": "태국,팟타이,그린카레",
        "note": "어썸타이 여의도.",
    },
    {
        "name": "타이레스토랑 여의도점",
        "category": "태국",
        "distance_km": 1.0,
        "address": "서울 영등포구 여의도동",
        "naver_url": "",
        "price_level": "13000~22000원",
        "tags": "태국,정통,볶음",
        "note": "여의도 태국 정통 레스토랑.",
    },
    {
        "name": "탄탄탄 여의도점",
        "category": "태국",
        "distance_km": 0.8,
        "address": "서울 영등포구 여의도동",
        "naver_url": "",
        "price_level": "11000~16000원",
        "tags": "태국,팟타이,런치",
        "note": "여의도 태국 런치 후보.",
    },
    {
        "name": "그린타이 여의도점",
        "category": "태국",
        "distance_km": 1.1,
        "address": "서울 영등포구 여의도동",
        "naver_url": "",
        "price_level": "12000~18000원",
        "tags": "태국,그린카레,코코넛",
        "note": "여의도 태국 그린카레 전문.",
    },

    # ── 분식 (추가) ──────────────────────────────────────────────────────────
    {
        "name": "죠스떡볶이 여의도점",
        "category": "분식",
        "distance_km": 1.0,
        "address": "서울 영등포구 여의도역 인근",
        "naver_url": "",
        "price_level": "7000~12000원",
        "tags": "떡볶이,분식,체인",
        "note": "죠스떡볶이 체인.",
    },
    {
        "name": "신전떡볶이 여의도역점",
        "category": "분식",
        "distance_km": 1.0,
        "address": "서울 영등포구 여의도역 인근",
        "naver_url": "",
        "price_level": "7000~12000원",
        "tags": "떡볶이,치즈,분식",
        "note": "신전떡볶이 체인.",
    },
    {
        "name": "엽기떡볶이 여의도직영점",
        "category": "분식",
        "distance_km": 1.1,
        "address": "서울 영등포구 여의도동",
        "naver_url": "",
        "price_level": "9000~15000원",
        "tags": "떡볶이,엽기,매운맛",
        "note": "엽기떡볶이 체인.",
    },
    {
        "name": "이삭토스트 여의도역점",
        "category": "분식",
        "distance_km": 1.0,
        "address": "서울 영등포구 여의도역 인근",
        "naver_url": "",
        "price_level": "5000~9000원",
        "tags": "토스트,아침,가성비",
        "note": "이삭토스트 체인.",
    },
    {
        "name": "봉구스밥버거 여의도역점",
        "category": "분식",
        "distance_km": 1.0,
        "address": "서울 영등포구 여의도역 인근",
        "naver_url": "",
        "price_level": "5000~9000원",
        "tags": "밥버거,분식,빠른점심",
        "note": "봉구스밥버거 체인.",
    },
    {
        "name": "김밥나라 여의도역점",
        "category": "분식",
        "distance_km": 1.0,
        "address": "서울 영등포구 여의도역 인근",
        "naver_url": "",
        "price_level": "5000~10000원",
        "tags": "김밥,라면,분식",
        "note": "김밥나라 체인.",
    },
    {
        "name": "오니기리와이규동 여의도점",
        "category": "분식",
        "distance_km": 0.9,
        "address": "서울 영등포구 여의도동",
        "naver_url": "",
        "price_level": "6000~11000원",
        "tags": "오니기리,규동,가벼운점심",
        "note": "오니기리와이규동 체인.",
    },

    # ── 카페 (추가) ──────────────────────────────────────────────────────────
    {
        "name": "스타벅스 여의도IFC점",
        "category": "카페",
        "distance_km": 0.9,
        "address": "서울 영등포구 국제금융로 10 IFC몰",
        "naver_url": "",
        "price_level": "8000~15000원",
        "tags": "카페,샌드위치,IFC몰",
        "note": "IFC몰 스타벅스. 간단한 점심 가능.",
    },
    {
        "name": "폴바셋 여의도IFC점",
        "category": "카페",
        "distance_km": 0.9,
        "address": "서울 영등포구 국제금융로 10 IFC몰",
        "naver_url": "",
        "price_level": "9000~18000원",
        "tags": "카페,브런치,IFC몰,커피",
        "note": "IFC몰 폴바셋. 브런치 세트 있음.",
    },
    {
        "name": "투썸플레이스 여의도IFC점",
        "category": "카페",
        "distance_km": 0.9,
        "address": "서울 영등포구 국제금융로 10 IFC몰",
        "naver_url": "",
        "price_level": "8000~15000원",
        "tags": "카페,케이크,IFC몰",
        "note": "IFC몰 투썸플레이스.",
    },
    {
        "name": "이디야커피 여의도점",
        "category": "카페",
        "distance_km": 0.8,
        "address": "서울 영등포구 국제금융로 일대",
        "naver_url": "",
        "price_level": "5000~10000원",
        "tags": "카페,가성비,샌드위치",
        "note": "이디야 체인. 가성비 카페 점심.",
    },
    {
        "name": "빽다방 여의도역점",
        "category": "카페",
        "distance_km": 1.0,
        "address": "서울 영등포구 여의도역 인근",
        "naver_url": "",
        "price_level": "4000~8000원",
        "tags": "카페,저렴,커피",
        "note": "빽다방 체인.",
    },
    {
        "name": "메가커피 여의도역점",
        "category": "카페",
        "distance_km": 1.0,
        "address": "서울 영등포구 여의도역 인근",
        "naver_url": "",
        "price_level": "4000~8000원",
        "tags": "카페,저렴,빠른점심",
        "note": "메가커피 체인.",
    },
    {
        "name": "컴포즈커피 여의도점",
        "category": "카페",
        "distance_km": 0.9,
        "address": "서울 영등포구 여의도동",
        "naver_url": "",
        "price_level": "4000~8000원",
        "tags": "카페,저렴",
        "note": "컴포즈커피 체인.",
    },
    {
        "name": "더벤티 여의도점",
        "category": "카페",
        "distance_km": 0.9,
        "address": "서울 영등포구 여의도동",
        "naver_url": "",
        "price_level": "4000~8000원",
        "tags": "카페,저렴,대용량",
        "note": "더벤티 체인.",
    },

    # ── 양식 (추가) ──────────────────────────────────────────────────────────
    {
        "name": "맥도날드 여의도역점",
        "category": "양식",
        "distance_km": 1.0,
        "address": "서울 영등포구 여의도역 인근",
        "naver_url": "",
        "price_level": "7000~13000원",
        "tags": "버거,패스트푸드,빠른점심",
        "note": "맥도날드 여의도역점.",
    },
    {
        "name": "버거킹 여의도점",
        "category": "양식",
        "distance_km": 1.0,
        "address": "서울 영등포구 여의도역 인근",
        "naver_url": "",
        "price_level": "8000~14000원",
        "tags": "버거,패스트푸드,빠른점심",
        "note": "버거킹 여의도점.",
    },

    # ── 기타 (추가) ──────────────────────────────────────────────────────────
    {
        "name": "온더보더 여의도IFC점",
        "category": "기타",
        "distance_km": 0.9,
        "address": "서울 영등포구 국제금융로 10 IFC몰",
        "naver_url": "",
        "price_level": "15000~25000원",
        "tags": "멕시칸,타코,부리또,IFC몰",
        "note": "IFC몰 온더보더 멕시칸 레스토랑.",
    },
    {
        "name": "마라공방 여의도점",
        "category": "기타",
        "distance_km": 1.0,
        "address": "서울 영등포구 여의도동",
        "naver_url": "",
        "price_level": "12000~20000원",
        "tags": "마라탕,마라,중식",
        "note": "여의도 마라탕 전문.",
    },
    {
        "name": "향미 여의도점",
        "category": "기타",
        "distance_km": 1.0,
        "address": "서울 영등포구 여의도동",
        "naver_url": "",
        "price_level": "11000~18000원",
        "tags": "마라탕,마라,향미",
        "note": "여의도 마라탕 향미 체인.",
    },
    {
        "name": "인도요리 사브리나 여의도점",
        "category": "기타",
        "distance_km": 1.1,
        "address": "서울 영등포구 여의도동",
        "naver_url": "",
        "price_level": "13000~22000원",
        "tags": "인도카레,난,탄두리",
        "note": "여의도 인도 카레 전문.",
    },
    {
        "name": "샐러디 여의도점",
        "category": "기타",
        "distance_km": 0.8,
        "address": "서울 영등포구 국제금융로 일대",
        "naver_url": "",
        "price_level": "10000~16000원",
        "tags": "샐러드,건강식,가벼운점심",
        "note": "샐러디 체인. 여의도 샐러드 점심.",
    },
    {
        "name": "맘스터치 여의도점",
        "category": "기타",
        "distance_km": 1.0,
        "address": "서울 영등포구 여의도역 인근",
        "naver_url": "",
        "price_level": "7000~13000원",
        "tags": "치킨버거,패스트푸드",
        "note": "맘스터치 체인. 여의도역 인근.",
    },

    # ── 일식 (추가) ──────────────────────────────────────────────────────────
    {
        "name": "스시로 여의도점",
        "category": "일식",
        "distance_km": 1.0,
        "address": "서울 영등포구 여의도동",
        "naver_url": "",
        "price_level": "12000~25000원",
        "tags": "회전초밥,스시,일식",
        "note": "스시로 체인 여의도점.",
    },
    {
        "name": "하코야 여의도점",
        "category": "일식",
        "distance_km": 0.9,
        "address": "서울 영등포구 여의도동",
        "naver_url": "",
        "price_level": "11000~18000원",
        "tags": "꼬치,이자카야,일식",
        "note": "하코야 체인. 점심 가능.",
    },
]


def seed_yeouido_restaurants() -> int:
    init_db()
    delete_restaurants_by_names(DEMO_RESTAURANT_NAMES + LEGACY_VARIANT_NAMES)

    inserted = 0
    for payload in CURATED_RESTAURANTS:
        upsert_restaurant_by_name(prepare_restaurant_payload(payload))
        inserted += 1
    return inserted
